#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Terremoto Centro Italia

# Short bio or description (displayed in the header)
description: un progetto per informare sul terremoto del 24 Agosto 2016

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: https://www.facebook.com/groups/1758670357733881/
  flickr:
  github: emergenzeHack/terremotocentro
  instagram:
  linkedin:
  pinterest:
  rss: https://script.googleusercontent.com/macros/echo?user_content_key=8A9trJymEqqgaZeneAXsFEMsIfhokJdg2KSMD6VuttCRpt2ekRI_Tb1iK8df1PfxQA0UTHUhOSKG5eQVm02SHL8QYWTG6oOTm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnNEUEbJV1q2qpuLLdUp01ulQjRhQsOczJFNuFYetZXGa7OPL6k4ZOUBLPsfd8vtj5uIqWsDnSrEd&lib=MrhRbXuMyxTPmH4TcJxedWzcqYDhQuE81
  twitter: terremotocentro
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://emergenzehack.github.io/terremotocentro

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/terremotocentro"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
